/* Organ views for the Bedside Assessment Atlas: tap a structure and the figure flies in on that organ, lights it with its
   own parts and supply, and the panel describes its anatomy the way a nurse meets it at the bedside.
   Fields · match: names lit in the view (everything else fades) · own: names that open this view when tapped (defaults to match)
   · layers: anatomy layers switched on · parts: [regex, label, note] in the order they are listed · where: surface anatomy
   · assess: bedside points · regions / tools / conds: atlas links · cam: optional [target, distance] camera override.
   General nursing reference. Local policy always wins. */
window.ORGAN_VIEWS=[
{id:'heart',name:'Heart',sys:'cardio',layers:['organ','artery','vein'],
 own:/atrium|ventricle|Heart valves|Coronary arteries|Cardiac veins/i,
 match:/atrium|ventricle|Heart valves|Coronary arteries|Cardiac veins|Pulmonary trunk|Ascending aorta|Aortic arch|Superior vena cava|Pulmonary veins/i,
 blurb:'A four-chamber muscular pump the size of a fist, sitting behind the sternum with two-thirds to the patient\'s left. Right side receives venous blood and sends it to the lungs; left side receives oxygenated blood and drives it round the body.',
 parts:[[/Right atrium/i,'Right atrium','Receives the venae cavae and the coronary sinus. Holds the sinoatrial node, so rhythm problems start here: think AF, flutter, sick sinus.'],
  [/Right ventricle/i,'Right ventricle','Thin-walled, lies directly behind the sternum. Pumps to the pulmonary trunk. Fails with pulmonary embolus, COPD and left heart failure: raised JVP, peripheral oedema, hepatomegaly.'],
  [/Left atrium/i,'Left atrium','Most posterior chamber, receives the four pulmonary veins. Dilates in mitral disease and long-standing AF; clot forms in its appendage, hence anticoagulation.'],
  [/Left ventricle/i,'Left ventricle','Thick-walled workhorse. Its apex is the apex beat: 5th intercostal space, mid-clavicular line. Failure gives breathlessness, orthopnoea and crackles at the bases.'],
  [/Heart valves/i,'Valves','Tricuspid and mitral between atria and ventricles; pulmonary and aortic at the outflows. Murmurs are turbulent flow: listen at the four areas with the patient leaning forward, then on the left side.'],
  [/Coronary arteries/i,'Coronary arteries','Right and left (LAD and circumflex) arise from the aortic root and fill in diastole. Occlusion is a heart attack: chest pain, sweating, nausea, or silent in older adults and diabetes.'],
  [/Cardiac veins/i,'Cardiac veins','Drain through the coronary sinus into the right atrium.'],
  [/Pulmonary trunk/i,'Pulmonary trunk','Carries venous blood from the right ventricle to both lungs. Blocked by embolus from a leg DVT.'],
  [/Ascending aorta|Aortic arch/i,'Aorta and arch','Leaves the left ventricle, arches over the left main bronchus and gives the brachiocephalic, left carotid and left subclavian arteries. Dissection: tearing chest or back pain with unequal arm pressures.'],
  [/Superior vena cava|Pulmonary veins/i,'Great veins','Superior vena cava returns blood from head and arms to the right atrium; pulmonary veins return oxygenated blood to the left atrium.']],
 where:'Between the 2nd and 5th ribs, behind the sternum. Aortic area right 2nd space, pulmonary area left 2nd space, tricuspid lower left sternal edge, mitral at the apex.',
 assess:['Rate, rhythm and volume at the radial pulse, then the apex beat: an apex-radial deficit means AF or ectopics.','Heart sounds at the four areas; new murmur with fever is endocarditis until proven otherwise.','Blood pressure both arms on first assessment; postural drop after one and three minutes standing.','JVP, ankle and sacral oedema, lung bases, daily weight: the heart failure set.','Chest pain: site, character, radiation, sweating, time of onset. ECG within 10 minutes and escalate.'],
 regions:['vitals','chest','limbs'],tools:['chestpain','vitalscalc','isbar'],conds:['cad','acs','hf','af','arrhythmia','valve','endocarditis','cardiomyopathy','htn','hypotension']},

{id:'lungs',name:'Lungs and airways',sys:'respiratory',layers:['organ','artery','vein'],
 own:/lung|Bronchial tree|Diaphragm/i,
 match:/lung|Trachea|Bronchial tree|Larynx|Pulmonary trunk|Pulmonary veins|Diaphragm/i,
 blurb:'Two spongy lungs fill the chest either side of the heart: three lobes on the right, two on the left, each fed by its own bronchus. They sit on the diaphragm and reach up above the clavicles.',
 parts:[[/Trachea/i,'Trachea','Midline from the larynx to the carina at the sternal angle. Deviation means tension pneumothorax or a large effusion pushing it away, or collapse pulling it across.'],
  [/Bronchial tree/i,'Bronchial tree','The right main bronchus is wider and more vertical, so inhaled food and misplaced tubes go right. Segmental bronchi lead to the lobes you auscultate.'],
  [/Right lung: superior/i,'Right upper lobe','Heard at the front above the 4th rib and at the apex behind. Classic site for TB and aspiration when lying flat.'],
  [/Right lung: middle/i,'Right middle lobe','Front only, between the 4th and 6th ribs. Listen in the right axilla; it is missed if you only listen at the back.'],
  [/Right lung: inferior/i,'Right lower lobe','Mostly at the back, from T3 down to T10. The usual site of basal crackles and pneumonia in the bed-bound.'],
  [/Left lung: superior/i,'Left upper lobe','Includes the lingula, the left lung\'s equivalent of a middle lobe, tucked against the heart.'],
  [/Left lung: inferior/i,'Left lower lobe','At the back and side. Bases are where fluid collects first: crackles that do not clear with a cough.'],
  [/Diaphragm/i,'Diaphragm','The main muscle of breathing, supplied by the phrenic nerve (C3, 4, 5). Splinted by pain, ascites or obesity; irritation refers pain to the shoulder tip.'],
  [/Pulmonary trunk|Pulmonary veins/i,'Pulmonary vessels','Low-pressure circuit between right and left heart. Embolus here gives sudden breathlessness, pleuritic pain and tachycardia with a clear chest.']],
 where:'Apices 2 to 3 cm above the clavicles; lower border at rib 6 in front, rib 8 at the side, rib 10 behind. The oblique fissure runs from T3 behind to rib 6 in front.',
 assess:['Rate first, counted for a full minute; then depth, rhythm, effort, ability to finish a sentence.','Oxygen saturation and its trend; know the target range and whether the patient retains CO2.','Expansion and symmetry, percussion, breath sounds and added sounds lobe by lobe, front, side and back.','Cough, sputum colour and volume, haemoptysis; airway threat is stridor, drooling, swelling.','Position matters: sit upright, lean forward. A silent chest in asthma is an emergency.'],
 regions:['chest','vitals','nose'],tools:['vitalscalc','primary','anaphylaxis'],conds:['copd','asthma','pneumonia','pe','pleural','bronchiectasis','lungca','osa','tb']},

{id:'airway',name:'Upper airway and throat',sys:'respiratory',layers:['organ','bone'],
 own:/Nasal cavity|Pharynx|Larynx|Soft palate|Tongue|Salivary|Teeth|Hyoid|Palatine tonsils/i,
 match:/Nasal cavity|Pharynx|Larynx|Soft palate|Tongue|Salivary|Teeth|Mandible|Hyoid|Palatine tonsils|Trachea/i,
 blurb:'Air and food share the pharynx; the larynx and epiglottis keep them apart. Swallowing, speech and the airway all depend on this short stretch of anatomy.',
 parts:[[/Nasal cavity/i,'Nasal cavity','Warms, filters and humidifies air. Blocked by polyps, a deviated septum or swelling; the usual route for oxygen prongs and NG tubes.'],
  [/Tongue/i,'Tongue','Falls back and blocks the airway in the unconscious: the reason for the head tilt and chin lift. Dry, coated or ulcerated tongue tells you about hydration and oral care.'],
  [/Soft palate/i,'Soft palate and uvula','Lifts to close the nose during swallowing. Deviation of the uvula points to a vagus lesion or a peritonsillar abscess.'],
  [/Salivary/i,'Salivary glands','Parotid, submandibular and sublingual. Dry mouth from anticholinergic drugs is a falls, dental and swallowing risk.'],
  [/Palatine tonsils/i,'Tonsils','Lymphoid tissue either side of the throat; enlarged and exudative in tonsillitis and glandular fever.'],
  [/Pharynx/i,'Pharynx','Naso-, oro- and laryngopharynx. Pooling of secretions, wet voice after swallowing and coughing on fluids are the aspiration flags.'],
  [/Larynx/i,'Larynx','Voice box and airway guard, at C3 to C6. Stridor is a narrowed larynx or trachea and needs immediate escalation.'],
  [/Hyoid|Mandible|Teeth/i,'Jaw, hyoid and teeth','The mandible anchors the tongue; a receding chin and small mouth make airway management harder. Loose teeth and dentures are an airway risk when drowsy.']],
 where:'Larynx behind the thyroid cartilage (Adam\'s apple) at C4 to C5; cricoid ring below it at C6. Trachea starts at C6 and enters the chest at the sternal notch.',
 assess:['Airway first: talking normally means patent. Snoring, gurgling or stridor means not.','Swallow screen before anything by mouth after stroke or when drowsy: sips of water, watch for cough, wet voice, delay.','Mouth care: lips, tongue, mucosa, teeth and dentures, saliva. Score it and act on it.','Voice change, drooling, trismus, neck swelling: escalate.'],
 regions:['mouth','nose','neck','vitals'],tools:['primary','anaphylaxis','must'],conds:['dysphagia','oral','osa','gord','peg']},

{id:'brain',name:'Brain',sys:'neuro',layers:['organ','artery','vein','bone'],
 own:/^(?!.*lung)(.*(lobe|Cerebrum|Cerebellum|Brainstem|Pituitary|Pineal))/i,
 match:/^(?!.*lung)(.*(lobe|Cerebrum|Cerebellum|Brainstem|Pituitary|Pineal|Cerebral arteries|Dural venous))/i,cam:[[0,8.2,0.3],5.5],
 blurb:'About 1.4 kg of brain inside a rigid skull. Each lobe has a job, the two hemispheres control the opposite side of the body, and the blood supply comes up through the carotid and vertebral arteries to the circle of Willis.',
 parts:[[/Frontal lobe/i,'Frontal lobe','Movement (motor strip), speech production (Broca\'s, usually left), planning, judgement and personality. Frontal damage: disinhibition, apathy, expressive dysphasia.'],
  [/Parietal lobe/i,'Parietal lobe','Sensation and spatial awareness. Right parietal stroke gives neglect of the left side: the patient ignores food on half the plate.'],
  [/Temporal lobe/i,'Temporal lobe','Hearing, memory and language comprehension (Wernicke\'s). Temporal seizures give déjà vu, smells and lip smacking.'],
  [/Occipital lobe/i,'Occipital lobe','Vision. Damage gives visual field loss on the opposite side, often unnoticed by the patient.'],
  [/Cerebrum:/i,'Deep structures','Basal ganglia (Parkinson\'s), thalamus (sensation relay), internal capsule (the classic small stroke with dense hemiplegia) and hypothalamus (temperature, thirst, hormones).'],
  [/Cerebellum/i,'Cerebellum','Balance and coordination. Cerebellar signs: ataxia, intention tremor, nystagmus, slurred speech; a cerebellar bleed can obstruct the ventricles quickly.'],
  [/Brainstem/i,'Brainstem','Midbrain, pons and medulla: breathing, heart rate, consciousness and the cranial nerves. Pressure here from swelling is what kills in head injury: pupils, breathing pattern and Cushing\'s triad.'],
  [/Pituitary/i,'Pituitary','Sits in the sella under the brain. Tumours press on the optic chiasm (loss of outer visual fields) and disturb thyroid, adrenal, growth and water hormones.'],
  [/Pineal/i,'Pineal gland','Melatonin and sleep-wake timing.'],
  [/Cerebral arteries/i,'Cerebral arteries','Circle of Willis joins the carotid and vertebral supply. Middle cerebral artery strokes are the common ones: face and arm weakness, speech loss.'],
  [/Dural venous/i,'Dural venous sinuses','Drain the brain into the internal jugular veins. Thrombosis presents as severe headache with raised pressure.'],
  [/Skull/i,'Skull (ghosted)','Rigid box: swelling or bleeding has nowhere to go, so a falling GCS matters more than the injury looks. Tap it to open the skull view.']],
 where:'Frontal lobe behind the forehead, temporal lobe under the temple, parietal under the crown, occipital at the back; cerebellum under the occipital bone; brainstem in front of it, continuing as the cord through the foramen magnum.',
 assess:['Consciousness with ACVPU then GCS, and the trend over time; a two-point drop is a call.','Pupils: size, equality, reaction. A new fixed dilated pupil is the same side as the pressure.','FAST: face, arm, speech, time. New deficit is a stroke call whatever the hour.','Headache red flags: thunderclap, worst ever, with fever, neck stiffness, vomiting or after a fall on anticoagulants.','Delirium screen (4AT) on admission and with any change in behaviour.'],
 regions:['neuro','eyes','head'],tools:['gcs','acvpu','stroke','4at','minicog','mse'],conds:['subdural','epilepsy','parkinsons','dementia','headache','vertigo','di']},

{id:'eye',name:'Eye and orbit',sys:'neuro',layers:['organ','nerve','vein'],
 own:/Eyeball|Optic nerve|Oculomotor|Orbital veins/i,match:/Eyeball|Optic nerve|Oculomotor|Orbital veins|Olfactory/i,cam:[[0,7.95,1.0],4.2],
 blurb:'The eyeball sits in a bony orbit, moved by six muscles and three cranial nerves, with the optic nerve running back to the brain. It is the most accessible window onto the nervous system.',
 parts:[[/Eyeball/i,'Eyeball','Cornea and lens focus onto the retina. Sudden painless loss of vision is vascular; painful red eye with a fixed mid-sized pupil is acute glaucoma.'],
  [/Optic nerve/i,'Optic nerve (II)','Carries vision to the occipital lobe. Test each eye separately: acuity, fields by confrontation, pupil reaction (the afferent limb).'],
  [/Oculomotor/i,'Nerves III, IV, VI','Move the eye and lift the lid; III also constricts the pupil. A dilated pupil with a drooping lid is a III palsy: think aneurysm or raised pressure.'],
  [/Orbital veins/i,'Orbital veins','Drain to the cavernous sinus, the route by which facial infection can spread inward.'],
  [/Olfactory/i,'Olfactory nerve (I)','Smell; lost after head injury and in early Parkinson\'s and COVID.']],
 where:'Orbit rimmed by the frontal bone above and the cheekbone below. The optic nerve leaves at the back of the orbit toward the pituitary and chiasm.',
 assess:['Acuity with their glasses, one eye at a time; fields by confrontation.','Pupils PEARL, then eye movements in an H: diplopia, nystagmus, restricted gaze.','Red eye: pain, photophobia, discharge, vision change. Painful loss of vision is urgent.','Ptosis, facial droop, lid closure: pair with the facial nerve exam.'],
 regions:['eyes','neuro','head'],tools:['gcs','stroke'],conds:['cataract','redeye','bell','headache']},

{id:'thyroid',name:'Thyroid and neck',sys:'endocrine',layers:['organ','artery','vein','bone'],
 own:/Thyroid gland|Parathyroid/i,match:/Thyroid gland|Parathyroid|Larynx|Trachea|Common carotid|Internal jugular|Hyoid|Cervical vertebrae/i,cam:[[0,6.55,0.4],4.8],
 blurb:'A butterfly of two lobes joined across the trachea just below the larynx, with four rice-grain parathyroids on its back. It sets the metabolic rate; the parathyroids set the calcium.',
 parts:[[/Thyroid gland/i,'Thyroid gland','Moves up on swallowing, which is how you tell a thyroid lump from anything else in the neck. Overactive: weight loss, tremor, heat, fast AF. Underactive: fatigue, cold, weight gain, slow pulse, low mood.'],
  [/Parathyroid/i,'Parathyroid glands','Parathyroid hormone raises calcium. Removed or damaged at thyroid surgery: tingling, cramps, Chvostek and Trousseau signs within a day or two.'],
  [/Larynx|Trachea/i,'Larynx and trachea','A large goitre can compress the trachea (stridor, breathless lying flat) or the recurrent laryngeal nerve (hoarse voice).'],
  [/Common carotid|Internal jugular/i,'Carotid sheath','The common carotid artery and internal jugular vein run beside the thyroid. Carotid pulse here; JVP read from the internal jugular.'],
  [/Hyoid|Cervical vertebrae/i,'Hyoid and cervical spine','Landmarks: hyoid at C3, thyroid cartilage at C4 to C5, cricoid at C6, thyroid isthmus over rings 2 to 4.']],
 where:'Isthmus over the 2nd to 4th tracheal rings, just below the cricoid; lobes either side up to the thyroid cartilage. Inspect from the front, palpate from behind while the patient swallows.',
 assess:['Look while they swallow, then palpate from behind; note size, nodules, tenderness and whether it moves.','Pulse and rhythm, tremor, sweating, eye signs, reflexes: the thyroid status clues.','After thyroid surgery: voice, stridor, neck swelling, calcium symptoms.','Thyroid bloods tie in with new AF, unexplained weight change, depression and confusion in older adults.'],
 regions:['neck','vitals','neuro'],tools:['vitalscalc'],conds:['hypothyroid','hyperthyroid','thyroidnodule','calcium','af']},

{id:'spine',name:'Spine and spinal cord',sys:'neuro',layers:['bone','nerve','levels'],
 own:/vertebrae|Sacrum|Spinal cord|Cauda equina/i,match:/vertebrae|Sacrum|Spinal cord|Cauda equina|Lumbar nerves|Intercostal|Cervical nerves|Sympathetic trunk/i,cam:[[0,3.4,-0.2],17],
 blurb:'Thirty-three vertebrae stacked on discs protect the spinal cord, which ends at L1 to L2 and continues as the cauda equina. Each level gives off a pair of nerves; the level of a deficit tells you where the problem is.',
 parts:[[/Cervical vertebrae/i,'Cervical spine C1–C7','C1 and C2 let the head nod and turn. Injury above C5 threatens the diaphragm; the ladder on the figure shows each level.'],
  [/Thoracic vertebrae/i,'Thoracic spine T1–T12','Each carries a rib. Osteoporotic wedge fractures happen here: sudden mid-back pain, loss of height, kyphosis.'],
  [/Lumbar vertebrae/i,'Lumbar spine L1–L5','Bears the load; discs and facet joints wear. Sciatica is L4 to S1 root pain down the leg past the knee.'],
  [/Sacrum/i,'Sacrum and coccyx','Five fused vertebrae wedged between the hip bones; the sacrum is the commonest pressure injury site in the bed-bound.'],
  [/Spinal cord/i,'Spinal cord','Runs from the brainstem to L1 to L2. Compression is an emergency: back pain, leg weakness, numbness, new incontinence or retention.'],
  [/Cauda equina/i,'Cauda equina','The horse\'s tail of lumbar and sacral roots below the cord. Saddle numbness, urinary retention and bilateral leg symptoms need same-day imaging.'],
  [/Cervical nerves|Intercostal|Lumbar nerves/i,'Spinal nerves','Cervical plexus (C1 to C4, including the phrenic nerve), intercostal nerves (T1 to T12, the dermatome bands used to grade sensory level) and lumbar nerves.'],
  [/Sympathetic trunk/i,'Sympathetic trunk','Autonomic chain either side of the spine. Cord injury above T6 risks autonomic dysreflexia: sudden severe hypertension with headache and sweating.']],
 where:'C7 is the first prominent bump at the base of the neck; T3 level with the spine of the scapula; T7 at its lower angle; L4 at the top of the iliac crests; S2 at the dimples.',
 assess:['After a fall or trauma: midline tenderness, step or deformity, any new neurology means immobilise and escalate.','Power, tone, reflexes and sensation by level and side; compare with the ladder on the figure.','Ask about bladder and bowel every time back pain comes with leg symptoms.','Dermatome map for pain and numbness; a clear sensory level is a cord lesion until proven otherwise.'],
 regions:['back','neuro','msk','pain'],tools:['secondary','gcs','frat'],conds:['cordcomp','backpain','fracture','osteoporosis','neuropathy']},

{id:'stomach',name:'Oesophagus and stomach',sys:'digestive',layers:['organ','artery'],
 own:/Oesophagus|Stomach/i,match:/Oesophagus|Stomach|Duodenum|Coeliac trunk|Diaphragm/i,cam:[[0.2,3.9,0.4],7.5],
 blurb:'The oesophagus carries food 25 cm from the pharynx through the diaphragm to the stomach, which churns it with acid under the left ribs before releasing it into the duodenum.',
 parts:[[/Oesophagus/i,'Oesophagus','Passes behind the heart and through the diaphragm at T10. Reflux, hiatus hernia and strictures give heartburn and food sticking; varices in liver disease bleed heavily.'],
  [/Stomach/i,'Stomach','Under the left dome of the diaphragm, fundus up against the heart. Ulcers and gastritis: epigastric pain, nausea, coffee-ground vomit or black stool. NG tubes end here.'],
  [/Duodenum/i,'Duodenum','C-shaped first part of the small bowel wrapping the head of the pancreas; bile and pancreatic juice enter here. Duodenal ulcer pain eases with food and wakes at night.'],
  [/Coeliac trunk/i,'Coeliac trunk','First big branch of the abdominal aorta: hepatic, splenic and left gastric arteries supply this whole region.'],
  [/Diaphragm/i,'Diaphragm','The oesophageal hiatus is where a hiatus hernia slips through.']],
 where:'Epigastrium and left upper quadrant. The stomach lies under ribs 5 to 9 on the left; the oesophagus enters it at the cardia just left of the midline.',
 assess:['Nausea, vomiting, character and timing; haematemesis or melaena is a bleed until proven otherwise.','Epigastric tenderness, distension, bowel sounds; rigidity and silence is a perforation.','Swallowing: food sticking, pain, regurgitation, weight loss. Dysphagia to solids progressing to liquids is a red flag.','NG or PEG: position check, aspirate pH, skin at the site, output.'],
 regions:['abdomen','mouth','vitals'],tools:['must','secondary'],conds:['gord','pud','gibleed','dysphagia','peg','malnutrition']},

{id:'liver',name:'Liver and biliary tree',sys:'digestive',layers:['organ','vein','artery'],
 own:/^Liver$|Gallbladder|Hepatic veins|Portal system/i,match:/^Liver$|Gallbladder|Hepatic veins|Portal system|Coeliac trunk|Inferior vena cava/i,cam:[[-0.2,3.8,0.4],7.5],
 blurb:'The largest organ inside the body, tucked under the right ribs. It receives the gut\'s blood through the portal vein, makes clotting factors and albumin, clears drugs and toxins, and stores bile in the gallbladder.',
 parts:[[/^Liver$/i,'Liver','Normally hidden by the ribs; a palpable edge below the costal margin is enlargement or a flattened diaphragm. Cirrhosis shrinks it and gives jaundice, ascites, bruising, confusion.'],
  [/Gallbladder/i,'Gallbladder and bile duct','Stores bile under the liver at the tip of the 9th costal cartilage. Stones: colicky right upper quadrant pain after fatty food, radiating to the right shoulder blade; Murphy\'s sign when inflamed.'],
  [/Portal system/i,'Portal vein','Brings nutrient-rich blood from the gut and spleen. Portal hypertension in cirrhosis backs up into oesophageal varices, a large spleen and ascites.'],
  [/Hepatic veins|Inferior vena cava/i,'Hepatic veins and IVC','Drain the liver into the inferior vena cava just below the heart. Right heart failure congests the liver: tender, enlarged and pulsatile.'],
  [/Coeliac trunk/i,'Hepatic artery','Branch of the coeliac trunk; the liver\'s oxygen supply.']],
 where:'Right upper quadrant, from the 5th rib in the mid-clavicular line down to the costal margin. Percuss the upper and lower borders; palpate from the right iliac fossa upward as the patient breathes in.',
 assess:['Skin and sclerae for jaundice; palms, spider naevi, bruising, gynaecomastia, ascites.','Right upper quadrant tenderness, Murphy\'s sign, liver span; fever with jaundice and pain is cholangitis.','Confusion or flapping tremor in known liver disease: encephalopathy, check for bleeding, infection, constipation.','Stool and urine colour, weight, alcohol history, paracetamol and drug review.'],
 regions:['abdomen','skin','vitals'],tools:['must','sepsis'],conds:['liver','gallbladder','gibleed','alcohol','pancreatitis']},

{id:'pancreas',name:'Pancreas and spleen',sys:'digestive',layers:['organ','artery','vein'],
 own:/Pancreas|Spleen/i,match:/Pancreas|Spleen|Duodenum|Coeliac trunk|Portal system/i,cam:[[0.2,3.4,0.3],7],
 blurb:'The pancreas lies across the back of the upper abdomen behind the stomach, its head in the curve of the duodenum and its tail touching the spleen under the left ribs.',
 parts:[[/Pancreas/i,'Pancreas','Digestive enzymes into the duodenum and insulin into the blood. Pancreatitis: severe epigastric pain boring through to the back, vomiting, eased by sitting forward. Head-of-pancreas cancer gives painless jaundice.'],
  [/Spleen/i,'Spleen','Under ribs 9 to 11 on the left, behind the stomach; filters blood and holds immune cells. Enlarges in infection, liver disease and blood cancers; rupture after rib trauma bleeds fast. No spleen means high sepsis risk.'],
  [/Duodenum/i,'Duodenum','Wraps the pancreatic head; the common bile duct passes through the head to open here.'],
  [/Coeliac trunk|Portal system/i,'Splenic vessels','Splenic artery and vein run along the back of the pancreas; the splenic vein joins the portal vein.']],
 where:'Pancreas at the level of L1 to L2, behind the stomach; not palpable. Spleen under the left costal margin, palpable only when enlarged and it comes toward the right iliac fossa.',
 assess:['Blood glucose and ketones; new diabetes or brittle control in pancreatic disease.','Epigastric pain to the back, vomiting, tachycardia, distension: pancreatitis needs fluids and escalation.','Left upper quadrant fullness, early satiety, bruising, recurrent infection: enlarged spleen or absent spleen.','Steatorrhoea, weight loss, jaundice.'],
 regions:['abdomen','vitals'],tools:['hypo','sepsis','must'],conds:['pancreatitis','t1dm','t2dm','dkahhs','liver','bloodca','immuno']},

{id:'smallbowel',name:'Small bowel',sys:'digestive',layers:['organ','artery','vein'],
 own:/Jejunum/i,match:/Jejunum|Duodenum|Superior mesenteric artery|Portal system/i,cam:[[0,2.4,0.5],8],
 blurb:'Six metres of duodenum, jejunum and ileum coiled in the centre of the abdomen, hung from the mesentery. Nearly all absorption happens here.',
 parts:[[/Duodenum/i,'Duodenum','First 25 cm, fixed behind the peritoneum. Receives bile and pancreatic juice.'],
  [/Jejunum/i,'Jejunum and ileum','Upper left coils are jejunum, lower right ileum, ending at the ileocaecal valve. Coeliac disease and Crohn\'s live here; obstruction gives early vomiting and central colicky pain.'],
  [/Superior mesenteric artery/i,'Superior mesenteric artery','Supplies the whole small bowel and the right colon. Occlusion in AF or atherosclerosis: pain out of proportion to findings, then a silent rigid abdomen.'],
  [/Portal system/i,'Mesenteric veins','Drain to the portal vein and the liver.']],
 where:'Umbilical region and around it. Small bowel pain is felt centrally because it is midgut; it only localises once the peritoneum is involved.',
 assess:['Pain pattern: colicky and central, with vomiting early, points to small bowel; distension and constipation come later.','Bowel sounds tinkling then absent; abdominal X-ray shows dilated loops with valvulae across the full width.','Hydration and electrolytes with vomiting and high stoma output; ileostomy over 1.2 L a day needs review.','Weight, anaemia and diarrhoea in malabsorption.'],
 regions:['abdomen','bowel','vitals'],tools:['must','secondary'],conds:['bowelobs','coeliac','ibd','hernia','stoma','gastro']},

{id:'colon',name:'Large bowel',sys:'digestive',layers:['organ','artery'],
 own:/Caecum|colon/i,match:/Caecum|colon|Inferior mesenteric|Superior mesenteric/i,cam:[[0,2.2,0.4],8.5],
 blurb:'The colon frames the abdomen: caecum and ascending colon on the right, transverse across, descending and sigmoid on the left down to the rectum. It reclaims water and stores stool.',
 parts:[[/Caecum/i,'Caecum and appendix','Right iliac fossa. Appendicitis: central pain moving to McBurney\'s point, nausea, low fever, guarding; atypical and dangerous in older adults.'],
  [/Ascending colon/i,'Ascending colon','Right flank up to the hepatic flexure. Right-sided cancers bleed silently: anaemia and fatigue rather than a change in bowel habit.'],
  [/Transverse colon/i,'Transverse colon','Hangs across below the stomach; the part most often seen distended in ileus and toxic megacolon.'],
  [/Descending colon/i,'Descending colon','Left flank down to the sigmoid. Left-sided disease changes stool calibre and habit.'],
  [/Sigmoid colon/i,'Sigmoid colon and rectum','S-bend in the left iliac fossa into the pelvis. Diverticulitis (left-sided appendicitis), volvulus in the elderly and constipated, and most colorectal cancers.'],
  [/Superior mesenteric|Inferior mesenteric/i,'Mesenteric arteries','Superior supplies the right colon, inferior the left. The splenic flexure between them is the watershed that suffers first in low flow.']],
 where:'The nine abdominal regions: caecum in the right iliac fossa, hepatic flexure under the right ribs, splenic flexure higher under the left ribs, sigmoid in the left iliac fossa. Palpable faeces in the left colon is common in the constipated.',
 assess:['Last bowel action, Bristol type, blood or mucus; use a chart and act on three days without.','Inspect, auscultate, percuss then palpate all nine regions; tenderness, guarding, masses, distension.','Stoma: colour (pink and moist), output, skin, fit of the appliance.','PR bleeding, iron deficiency, change in habit over six weeks or weight loss: refer.'],
 regions:['bowel','abdomen'],tools:['must','abbey'],conds:['constipation','diverticular','crc','appendix','bowelobs','ibd','ibs','haemorrhoids','stoma','gastro']},

{id:'kidneys',name:'Kidneys and adrenals',sys:'urinary',layers:['organ','artery','vein'],
 own:/kidney|adrenal|Renal/i,match:/kidney|adrenal|Renal arteries|Renal veins|Renal pelvis|Abdominal aorta|Inferior vena cava/i,cam:[[0,3.1,0.1],7],
 blurb:'Two bean-shaped filters against the back wall of the abdomen at T12 to L3, the right slightly lower under the liver, each with an adrenal gland perched on top. Together they filter about 180 litres a day.',
 parts:[[/Right kidney/i,'Right kidney','Lower than the left because of the liver. Loin pain and fever here is pyelonephritis; colic radiating to the groin is a stone.'],
  [/Left kidney/i,'Left kidney','Under ribs 11 and 12 posteriorly; tender to a gentle fist over the renal angle when infected.'],
  [/Renal pelvis/i,'Renal pelvis and ureters','Urine collects in the pelvis and runs 25 cm down the ureters to the bladder. Stones lodge where the ureter narrows: at the pelvis, over the iliac vessels and at the bladder wall.'],
  [/adrenal/i,'Adrenal glands','Cortisol, aldosterone and adrenaline. Failure (Addison\'s, or stopping long-term steroids): weakness, hypotension, low sodium, high potassium, collapse. Excess: Cushing\'s.'],
  [/Renal arteries|Abdominal aorta/i,'Renal arteries','Straight off the aorta at L1; the kidneys take a fifth of cardiac output. Low blood pressure or NSAIDs and ACE inhibitors together drop filtration fast.'],
  [/Renal veins|Inferior vena cava/i,'Renal veins','Drain to the inferior vena cava; the left is longer and crosses in front of the aorta.']],
 where:'Renal angle between the 12th rib and the spine on each side. The kidneys are not normally palpable; the adrenals never are.',
 assess:['Urine output against 0.5 mL/kg/h, colour and clarity; fluid balance and daily weight.','Creatinine and potassium trend; hold nephrotoxic drugs when unwell (sick-day rules).','Loin tenderness, fever, rigors, dysuria: pyelonephritis needs cultures and antibiotics quickly.','Postural hypotension, salt craving, pigmentation, or abrupt steroid withdrawal: think adrenal.'],
 regions:['urinary','abdomen','vitals','back'],tools:['sepsis','vitalscalc','qsofa'],conds:['aki','ckd','uti','stones','addison','cushing','phaeo','bladderca']},

{id:'bladder',name:'Bladder, prostate and pelvis',sys:'urinary',layers:['organ','bone'],
 own:/Urinary bladder|Prostate/i,match:/Urinary bladder|Prostate|Renal pelvis and ureters|Pelvis \(hip|Sacrum/i,cam:[[0,1.0,0.2],6.5],
 blurb:'The bladder sits behind the pubic bone and rises into the abdomen as it fills; in men the prostate wraps the urethra just below it. Both sit inside the bony pelvis with the rectum behind.',
 parts:[[/Urinary bladder/i,'Urinary bladder','Holds 400 to 600 mL; felt above the pubis once it passes about 300 mL and dull to percussion. Retention: distress, dribbling, a palpable dome, confusion in the elderly. Bladder scan before catheterising.'],
  [/Prostate/i,'Prostate','Walnut-sized gland around the urethra below the bladder. Enlargement gives hesitancy, poor stream, nocturia and retention; it is why male catheters can be hard to pass.'],
  [/Renal pelvis and ureters/i,'Ureters','Enter the bladder obliquely at the trigone, a valve against reflux.'],
  [/Pelvis \(hip/i,'Bony pelvis','Ilium, ischium and pubis fused into a ring; a fracture of one part usually means a break elsewhere in the ring and hidden blood loss.'],
  [/Sacrum/i,'Sacrum','Forms the back of the pelvic ring; the sacral nerves S2 to S4 control bladder, bowel and sexual function.']],
 where:'Suprapubic region. An empty bladder is not palpable; a full one is a smooth midline swelling from the pubis toward the umbilicus.',
 assess:['Frequency, urgency, dysuria, nocturia, stream, incontinence type; a bladder diary tells the story.','Palpate and percuss above the pubis; post-void residual by scanner, over 200 mL matters.','Catheter: indication still valid, securement, drainage, meatal care, CAUTI signs (fever, new confusion, cloudy urine).','New retention or incontinence with back pain or leg weakness: cauda equina until proven otherwise.'],
 regions:['urinary','pelvis','abdomen'],tools:['sepsis','4at','braden'],conds:['retention','incontinence','bph','uti','catheter','bladderca','cordcomp']},

{id:'aorta',name:'Aorta and major arteries',sys:'cardio',layers:['artery'],
 own:/aorta|Aortic arch|Common iliac arteries|Common carotid|Subclavian arteries|External iliac|Internal iliac/i,
 match:/aorta|Aortic arch|Common iliac arteries|Common carotid|Subclavian arteries|External iliac|Internal iliac|Coeliac|mesenteric artery|Renal arteries/i,cam:[[0,3.6,0.2],12],
 blurb:'The aorta rises from the left ventricle, arches over the heart and descends in front of the spine, giving branches to the head, arms, gut and kidneys before splitting into the iliac arteries at L4.',
 parts:[[/Ascending aorta|Aortic arch/i,'Ascending aorta and arch','Brachiocephalic, left common carotid and left subclavian arteries leave the arch. Dissection here: tearing chest pain to the back, pulse or pressure difference between arms, new neurology.'],
  [/Common carotid/i,'Common carotid arteries','Either side of the trachea; pulse felt at the level of the thyroid cartilage, one side at a time. Bruit means narrowing and stroke risk.'],
  [/Subclavian arteries/i,'Subclavian arteries','Under the clavicles to the arms; blood pressure difference over 20 mmHg between arms needs explaining.'],
  [/Thoracic \(descending\)/i,'Descending thoracic aorta','Runs down the left of the spine, giving intercostal arteries.'],
  [/Abdominal aorta/i,'Abdominal aorta','Palpable in thin people just left of the midline above the umbilicus. Aneurysm over 5.5 cm risks rupture: back or abdominal pain, collapse, a pulsatile expansile mass.'],
  [/Coeliac|mesenteric artery|Renal arteries/i,'Visceral branches','Coeliac trunk (foregut), superior mesenteric (midgut), renal arteries and inferior mesenteric (hindgut).'],
  [/Common iliac arteries|External iliac|Internal iliac/i,'Iliac arteries','Common iliacs split at L4; external iliacs become the femoral arteries at the inguinal ligament, internal iliacs supply the pelvis.']],
 where:'Arch at the sternal angle (T4). Abdominal aorta from the diaphragm (T12) to the umbilicus (L4), where it bifurcates.',
 assess:['Blood pressure in both arms; a pulse deficit or difference is dissection until proven otherwise.','Central pulses: carotid, femoral; peripheral pulses distal to any suspected block.','Pulsatile expansile abdominal mass, back pain and hypotension: call for help before anything else.','Smoking, blood pressure and lipids: the modifiable risks.'],
 regions:['vitals','abdomen','limbs','chest'],tools:['chestpain','vitalscalc','isbar'],conds:['aaa','htn','pad','cvrisk','acs']},

{id:'veins',name:'Venae cavae and great veins',sys:'cardio',layers:['vein'],
 own:/vena cava|Brachiocephalic|jugular|Subclavian veins|iliac veins|Azygos/i,
 match:/vena cava|Brachiocephalic|jugular|Subclavian veins|iliac veins|Azygos|Femoral vein|Hepatic veins|Renal veins/i,cam:[[0,3.6,0.2],12],
 blurb:'Blood returns through two great veins: the superior vena cava from head, neck and arms, the inferior vena cava from everything below the diaphragm. Both empty into the right atrium.',
 parts:[[/Internal jugular/i,'Internal jugular veins','Run beside the carotid arteries under the sternocleidomastoid. The JVP is read here at 45 degrees: raised in heart failure, fluid overload and tamponade.'],
  [/External jugular/i,'External jugular veins','Cross the sternocleidomastoid superficially; visible distension is a rough guide to venous pressure.'],
  [/Subclavian veins|Brachiocephalic/i,'Subclavian and brachiocephalic veins','Join behind the sternoclavicular joints to form the superior vena cava. Central lines and PICCs end just above the right atrium.'],
  [/Superior vena cava/i,'Superior vena cava','Obstruction by a lung tumour or line thrombus: swollen face and arms, distended chest veins, breathlessness worse lying flat.'],
  [/Inferior vena cava|Hepatic veins|Renal veins/i,'Inferior vena cava','Right of the aorta up through the liver to the heart; collects the renal and hepatic veins. Compressed by a pregnant uterus or large ascites when supine.'],
  [/iliac veins|Femoral vein/i,'Iliac and femoral veins','Route of clot from a leg DVT to the lungs.'],
  [/Azygos/i,'Azygos system','Drains the chest wall to the superior vena cava and bypasses a blocked inferior vena cava.']],
 where:'JVP: patient at 45 degrees, head turned slightly left, look for the double pulsation between the heads of the sternocleidomastoid; normal is under 3 cm above the sternal angle.',
 assess:['JVP height and waveform; hepatojugular reflux.','Line sites: redness, swelling, tenderness, arm or facial swelling on the side of a central line.','Calf tenderness, unilateral swelling over 3 cm, warmth: DVT until proven otherwise.','Facial plethora and distended chest wall veins: SVC obstruction, urgent.'],
 regions:['vitals','neck','limbs'],tools:['vitalscalc','isbar'],conds:['dvt','pe','hf','anticoag','venous']},

{id:'arm',name:'Arm: bones, vessels and nerves',sys:'muscular',layers:['bone','artery','vein','nerve'],
 own:/Humerus|Radius and ulna|Bones of the hand|Clavicles|Scapulae|Axillary|Brachial|Radial|Ulnar|Median nerve|Musculocutaneous|Cephalic|Basilic|Brachial plexus/i,
 match:/Humerus|Radius and ulna|Bones of the hand|Clavicles|Scapulae|Axillary|Brachial|Radial|Ulnar|Median nerve|Musculocutaneous|Cephalic|Basilic|Brachial plexus|Subclavian/i,cam:[[1.8,3.3,0.6],11],
 blurb:'From the clavicle and scapula through the humerus, radius and ulna to 27 bones in the hand, with the brachial plexus and its three great nerves and the brachial artery running down the inner arm.',
 parts:[[/Clavicles|Scapulae/i,'Shoulder girdle','Clavicle is the commonest bone broken in falls on the outstretched hand; the scapula floats on the ribs.'],
  [/Humerus/i,'Humerus','Neck fractures in older adults after a fall; the radial nerve winds round the shaft and is at risk in mid-shaft breaks (wrist drop).'],
  [/Radius and ulna/i,'Radius and ulna','Colles fracture of the distal radius is the classic osteoporotic fall injury: dinner-fork wrist.'],
  [/Bones of the hand/i,'Hand','Carpals, metacarpals and phalanges. Scaphoid fractures are missed on X-ray; tenderness in the anatomical snuffbox.'],
  [/Brachial plexus/i,'Brachial plexus','C5 to T1 roots pass between the scalenes and under the clavicle into the axilla. Injured by traction in shoulder dislocation and stretched by bad positioning.'],
  [/Axillary artery|Brachial artery/i,'Axillary and brachial arteries','Brachial pulse on the inner arm just above the elbow crease: the one you listen over for blood pressure and use in infants.'],
  [/Radial artery/i,'Radial artery','Radial pulse at the wrist on the thumb side; the site for arterial blood gases (check the ulnar supply with Allen\'s test first).'],
  [/Ulnar artery/i,'Ulnar artery','Little-finger side of the wrist; completes the palmar arches with the radial.'],
  [/Median nerve/i,'Median nerve','Runs down the front of the arm through the carpal tunnel. Carpal tunnel: numb thumb, index and middle fingers, worse at night.'],
  [/Ulnar nerve/i,'Ulnar nerve','Behind the medial epicondyle (the funny bone). Numb little and ring fingers; pressure from arm rests and bed rails.'],
  [/Radial nerve|Axillary nerve|Musculocutaneous/i,'Radial, axillary and musculocutaneous nerves','Radial extends the wrist and fingers (Saturday-night palsy from an arm over a chair). Axillary: shoulder sensation and deltoid after dislocation.'],
  [/Cephalic|Basilic/i,'Cephalic and basilic veins','Cephalic on the thumb side, basilic on the inside; the median cubital joins them at the elbow, the usual cannula and blood-taking site.']],
 where:'Brachial pulse medial to the biceps tendon at the elbow; radial pulse lateral to the flexor carpi radialis tendon at the wrist; ulnar nerve in the groove behind the medial epicondyle.',
 assess:['Colour, warmth, capillary refill, radial pulse, sensation and movement below any injury, cast or cannula: the neurovascular set.','Grip strength and drift; compare sides; new weakness is a stroke call.','Cannula sites daily: phlebitis score, infiltration, extravasation.','Lymphoedema arm after axillary surgery: no blood pressure, cannulas or bloods on that side.'],
 regions:['limbs','msk','skin','neuro'],tools:['stroke','secondary','frat'],conds:['fracture','oa','ra','neuropathy','lymphoedema','cellulitis']},

{id:'leg',name:'Leg: bones, vessels and nerves',sys:'muscular',layers:['bone','artery','vein','nerve'],
 own:/Femur|Patella|Tibia and fibula|Bones of the foot|Femoral|Popliteal|tibial|Fibular|saphenous|Sciatic|Obturator|Lateral femoral|Deep femoral/i,
 match:/Femur|Patella|Tibia and fibula|Bones of the foot|Femoral|Popliteal|tibial|Fibular|saphenous|Sciatic|Obturator|Lateral femoral|Deep femoral|External iliac/i,cam:[[0,-3.4,0.4],17],
 blurb:'The femur, the body\'s longest bone, runs from the hip to the knee; the tibia carries the weight below it with the fibula alongside, down to 26 bones in the foot. The femoral vessels run down the inner thigh and the sciatic nerve down the back.',
 parts:[[/Femur/i,'Femur','Neck-of-femur fracture after a fall: the leg lies shortened and externally rotated and cannot be lifted straight. Shaft fractures can lose a litre of blood.'],
  [/Patella/i,'Patella','Kneecap in the quadriceps tendon; knee effusion swells around it.'],
  [/Tibia and fibula/i,'Tibia and fibula','The shin is subcutaneous, so tibial fractures are often open. The fibular neck carries the common fibular nerve: foot drop after casts or bed rails press on it.'],
  [/Bones of the foot/i,'Foot','Talus, calcaneus, tarsals, metatarsals and toes. Diabetic feet: pressure points under the metatarsal heads and heel, Charcot joints, ulcers.'],
  [/Femoral artery|Deep femoral|External iliac/i,'Femoral artery','Femoral pulse at the mid-inguinal point, halfway between the pubic symphysis and the anterior superior iliac spine; access site for angiography, so watch for bleeding and haematoma afterward.'],
  [/Popliteal artery/i,'Popliteal artery','Deep behind the knee; press with both hands with the knee slightly bent. Aneurysm here is the commonest peripheral aneurysm.'],
  [/Anterior tibial|Posterior tibial|Fibular \(peroneal\) artery/i,'Tibial arteries','Dorsalis pedis on top of the foot lateral to the extensor hallucis tendon; posterior tibial behind the medial malleolus. The pulses that grade peripheral arterial disease.'],
  [/Great saphenous|Small saphenous/i,'Saphenous veins','Great saphenous from the medial ankle up the inside of the leg to the groin; small saphenous up the back of the calf. Varicose veins and venous ulcers above the medial malleolus.'],
  [/Femoral vein|Popliteal vein|Tibial and fibular veins/i,'Deep veins','Where DVT forms: calf tenderness, swelling, warmth, one leg more than the other. Clot in the femoral or popliteal vein is what reaches the lungs.'],
  [/Sciatic/i,'Sciatic nerve','Largest nerve in the body, from the buttock down the back of the thigh. Sciatica is root pain along it; intramuscular injections go in the upper outer quadrant to miss it.'],
  [/Femoral nerve|Obturator|Lateral femoral/i,'Femoral, obturator and lateral cutaneous nerves','Femoral nerve powers the quadriceps and knee jerk (L2 to L4). Lateral femoral cutaneous: numb outer thigh from belts and obesity.'],
  [/Tibial nerve|Common fibular/i,'Tibial and common fibular nerves','Tibial: calf and sole, ankle jerk (S1). Common fibular: foot drop and numb top of the foot.']],
 where:'Femoral pulse at the mid-inguinal point; popliteal behind the knee; posterior tibial behind the medial malleolus; dorsalis pedis on the dorsum of the foot.',
 assess:['Neurovascular set below any injury or cast: colour, warmth, capillary refill, pulses, sensation, movement, pain out of proportion (compartment syndrome).','Shortened externally rotated leg after a fall: do not move, analgesia, escalate.','Calf swelling, tenderness and warmth compared with the other side: DVT.','Foot check in diabetes: pulses, sensation with a monofilament, skin between the toes, heels, footwear.','Leg ulcer: site and edge (venous above the medial malleolus, arterial on toes and pressure points), pulses, ABPI before compression.'],
 regions:['limbs','msk','skin','pain'],tools:['frat','braden','secondary'],conds:['fracture','dvt','pad','venous','ulcers','neuropathy','cellulitis','oa','amputation']},

{id:'skull',name:'Skull, face and jaw',sys:'skeletal',layers:['bone','nerve','artery'],
 own:/Skull|Mandible|Teeth|Trigeminal|Facial nerve|External carotid/i,
 match:/Skull|Mandible|Teeth|Hyoid|Trigeminal|Facial nerve|External carotid|Hypoglossal/i,cam:[[0,7.9,0.5],5.5],
 blurb:'The cranium protects the brain; the facial bones and mandible carry the eyes, nose, mouth and teeth. The trigeminal nerve feels the face and the facial nerve moves it.',
 parts:[[/Skull/i,'Skull (cranium)','Frontal, parietal, temporal and occipital bones. The temporal bone is thin over the middle meningeal artery: a blow to the temple can cause an extradural bleed with a lucid interval then collapse.'],
  [/Mandible/i,'Mandible','Hinges at the temporomandibular joint in front of the ear. Fractures after falls and assaults; dislocation with wide yawning.'],
  [/Teeth/i,'Teeth','Loose teeth, poor dentition and dentures affect nutrition, speech, aspiration risk and airway management.'],
  [/Hyoid/i,'Hyoid','Suspends the tongue and larynx; the only bone that touches no other.'],
  [/Trigeminal/i,'Trigeminal nerve (V)','Three divisions: forehead, cheek, jaw. Test light touch in each; trigeminal neuralgia is stabbing one-sided face pain; shingles in V1 threatens the eye.'],
  [/Facial nerve/i,'Facial nerve (VII)','Runs through the parotid to the muscles of expression. Bell\'s palsy drops the whole side including the forehead; a stroke spares the forehead.'],
  [/External carotid/i,'External carotid branches','Facial, temporal and occipital arteries. Temporal artery pulse in front of the ear; tender, thickened and pulseless in giant cell arteritis.'],
  [/Hypoglossal/i,'Hypoglossal nerve (XII)','Moves the tongue; it deviates toward the weak side.']],
 where:'Temporal pulse just in front of the tragus; TMJ just in front of the ear canal; angle of the jaw at C2 to C3; mastoid behind the ear (bruising here after head injury means a base-of-skull fracture).',
 assess:['Head injury: mechanism, loss of consciousness, vomiting, anticoagulants, GCS, pupils, bruising behind the ears or around the eyes, clear fluid from nose or ear.','Facial symmetry at rest and on smiling, eye closure and forehead raising: stroke versus Bell\'s.','Facial sensation in all three divisions; jaw pain on chewing and scalp tenderness in an older adult with headache: giant cell arteritis.','Mouth opening, dentition, swelling, trismus.'],
 regions:['head','neuro','mouth','ears'],tools:['gcs','stroke','secondary'],conds:['subdural','bell','pmr','headache','oral','shingles']},

{id:'thorax',name:'Rib cage and chest wall',sys:'skeletal',layers:['bone','nerve','organ'],
 own:/Ribs|Sternum|Costal cartilages/i,
 match:/Ribs|Sternum|Costal cartilages|Clavicles|Thoracic vertebrae|Intercostal|Diaphragm/i,cam:[[0,4.6,0.3],11],
 blurb:'Twelve pairs of ribs curve from the thoracic spine to the sternum through costal cartilages, making a cage that protects the heart and lungs and moves with every breath.',
 parts:[[/Sternum/i,'Sternum','Manubrium, body and xiphoid. The sternal angle (where the manubrium meets the body) marks rib 2, the aortic arch and the carina: count ribs from here. CPR compresses the lower half.'],
  [/Ribs/i,'Ribs','Ribs 1 to 7 reach the sternum, 8 to 10 join the cartilage above, 11 and 12 float. Fractures in older adults: pneumonia risk from shallow breathing; three or more together may flail.'],
  [/Costal cartilages/i,'Costal cartilages','Give the cage its spring. Costochondritis is a common, tender, benign cause of chest pain.'],
  [/Clavicles/i,'Clavicles','Landmark for the lung apices above and the subclavian vessels below.'],
  [/Thoracic vertebrae/i,'Thoracic spine','Each rib articulates with its vertebra; kyphosis reduces lung volume.'],
  [/Intercostal/i,'Intercostal nerves','Run under each rib with the artery and vein: chest drains and needles go over the top of the rib below. Shingles follows one dermatome band.'],
  [/Diaphragm/i,'Diaphragm','Dome rises to rib 5 on the right in expiration, so the liver and spleen are protected by the lower ribs.']],
 where:'Sternal angle at rib 2; nipple at rib 4 in men; xiphoid at rib 7; the lowest rib you can feel in front is usually rib 10.',
 assess:['Chest wall pain: reproducible on pressing or twisting suggests the wall, but an ECG still rules out the heart.','After a fall or chest trauma: bruising, crepitus, paradoxical movement, breath sounds both sides, saturation.','Rib fracture care is analgesia and breathing exercises to prevent pneumonia.','Shape: barrel chest in COPD, kyphosis, pectus; expansion equal both sides.'],
 regions:['chest','vitals','back','pain'],tools:['chestpain','secondary','abbey'],conds:['fracture','osteoporosis','pleural','pneumonia','shingles','copd']},

{id:'diaphragm',name:'Diaphragm',sys:'respiratory',layers:['organ','nerve','bone'],own:/^Diaphragm$/i,match:/Diaphragm|Cervical nerves|Costal cartilages|Ribs/i,cam:[[0,3.7,0.3],9],
 blurb:'A dome of muscle separating chest from abdomen and doing most of the work of quiet breathing. Supplied by the phrenic nerves from C3, C4 and C5.',
 parts:[[/Diaphragm/i,'Diaphragm','Three openings: inferior vena cava at T8, oesophagus at T10, aorta at T12. Irritation (blood, pus, gallbladder) refers pain to the shoulder tip via the phrenic nerve.'],
  [/Cervical nerves/i,'Phrenic nerves','C3 to C5 keep the diaphragm alive: a neck injury above C5 means the patient cannot breathe unaided.'],
  [/Ribs|Costal cartilages/i,'Lower ribs','The diaphragm attaches around the lower six ribs and the xiphoid; rib pain splints it.']],
 where:'Right dome up to the 5th rib, left to the 6th in expiration. It descends 1 to 2 cm with quiet breathing, up to 10 cm with a deep breath.',
 assess:['Abdominal breathing pattern, use of accessory muscles, paradoxical movement of the abdomen on inspiration.','Breathlessness lying flat that improves sitting (orthopnoea) in weakness or paralysis of the diaphragm.','Hiccups that persist: irritation from below (distension, liver) or above (mediastinum).','Shoulder-tip pain with an abdominal problem.'],
 regions:['chest','abdomen','vitals'],tools:['vitalscalc'],conds:['pneumonia','copd','gallbladder','pleural']},

{id:'lymphnodes',name:'Lymph nodes and vessels',sys:'lymph',layers:['lymph','organ'],
 own:/nodes|Palatine tonsils|Thymus|lymph|Thoracic duct|Cisterna/i,match:/nodes|Palatine tonsils|Thymus|lymph|Thoracic duct|Cisterna/i,cam:[[0,2.8,0.2],21],
 blurb:'Lymph drains tissue fluid through chains of nodes back to the veins at the root of the neck. Nodes swell where they drain from, so where a node is tells you where to look.',
 parts:[[/Lymph nodes of the head|Cervical lymph/i,'Head and neck nodes','Submental, submandibular, pre- and post-auricular, occipital, then the deep cervical chain along the internal jugular vein. Drain the scalp, face, mouth and throat.'],
  [/Axillary and cubital/i,'Axillary and cubital nodes','Drain the arm and most of the breast; examine with the arm relaxed and supported. Removed in breast surgery, so that arm is at lymphoedema risk.'],
  [/Thoracic \(mediastinal\)/i,'Mediastinal nodes','Around the trachea and bronchi; enlarged in lung cancer, TB, sarcoid and lymphoma; not palpable.'],
  [/Abdominal lymph|Pelvic lymph/i,'Abdominal and pelvic nodes','Para-aortic and mesenteric chains; enlarge with gut and pelvic cancers and lymphoma.'],
  [/Inguinal and popliteal/i,'Inguinal and popliteal nodes','Groin nodes drain the leg, perineum and lower abdominal wall; small shotty groin nodes are normal. Popliteal nodes sit behind the knee.'],
  [/Palatine tonsils/i,'Tonsils','Lymphoid tissue guarding the throat.'],
  [/Thymus/i,'Thymus','Behind the sternum; large in children, fatty in adults. T-cells mature here.'],
  [/Thoracic duct|Cisterna|lymph trunk|Lymphatics|lymphatic duct|Bronchomediastinal/i,'Ducts and trunks','Lymph from the legs and gut collects in the cisterna chyli at L1 to L2 and climbs the thoracic duct to the left venous angle; the right lymphatic duct drains the right head, arm and chest.']],
 where:'Palpable groups: neck (front and back of the sternocleidomastoid, under the jaw, behind the ears, occiput), supraclavicular, axillary, epitrochlear, inguinal. A left supraclavicular node (Virchow\'s) points to abdominal cancer.',
 assess:['Site, size, consistency, tenderness, mobility: tender and mobile suggests infection, hard fixed and painless suggests cancer.','Fever, night sweats, unexplained weight loss and generalised nodes: refer.','Neutropenic sepsis in chemotherapy or immunosuppression: fever is an emergency.','Lymphoedema limb: skin care, no cannulas or cuffs on that side, watch for cellulitis.'],
 regions:['neck','limbs','skin'],tools:['sepsis','qsofa'],conds:['bloodca','cancer','immuno','lymphoedema','cellulitis','anaemia']}
];
